version: '3.1'

volumes:

  db-data:

services:

  db:
    image: mariadb
    restart: always
    ports:
      - "33006:3306"
    volumes:
      - "db-data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "r00tpa$$wd"
